import type { Project, Service, Certificate } from "@/types";

export const projects: Project[] = [
  {
    id: 1,
    title: "Bidoro Waitlist",
    description: "Landing page and waitlist signup for the Bidoro marketplace platform.",
    images: [
      "/images/bidoro-waitlist-1.png",
      "/images/bidoro-waitlist-2.png",
      "/images/bidoro-waitlist-3.png",
      "/images/bidoro-waitlist-4.png",
      "/images/bidoro-waitlist-5.png",
    ],
    tags: ["Next.js", "Node.js", "Express", "Supabase"],
    liveUrl: "https://bidoro.africa",
  },
  {
    id: 2,
    title: "Bidoro Marketplace",
    description: "Full-featured marketplace connecting buyers and sellers across Nigeria.",
    images: [
      "/images/bidoro-marketplace-1.png",
      "/images/bidoro-marketplace-2.png",
      "/images/bidoro-marketplace-3.png",
      "/images/bidoro-marketplace-4.png",
      "/images/bidoro-marketplace-5.png",
      "/images/bidoro-marketplace-6.png",
    ],
    tags: ["Next.js", "Node.js", "Express", "Supabase"],
    liveUrl: "https://staging.bidoro.africa/",
  },
  {
    id: 3,
    title: "Guardtrol Website",
    description: "Security management and tracking dashboard for guard patrol operations.",
    images: [
      "/images/guardtrol-1.png",
      "/images/guardtrol-2.png",
      "/images/guardtrol-3.png",
      "/images/guardtrol-4.png",
      "/images/guardtrol-5.png",
      "/images/guardtrol-6.png",
    ],
    tags: ["MongoDB", "Express", "React", "Node.js"],
    liveUrl: "https://guardtroltest.alphatrol.com/",
  },
  {
    id: 4,
    title: "Agent Logistics",
    description: "Specialised vehicle transport and haulage platform with real-time GPS tracking.",
    images: [
      "/images/agent-logistics-1.png",
      "/images/agent-logistics-2.png",
      "/images/agent-logistics-3.png",
      "/images/agent-logistics-4.png",
      "/images/agent-logistics-5.png",
      "/images/agent-logistics-6.png",
    ],
    tags: ["PHP", "HTML", "CSS"],
    liveUrl: "https://www.agentlogistic.com/",
  },
  {
    id: 5,
    title: "Stafftrol Website",
    description: "Staff management dashboard with attendance, payroll, and workforce tracking.",
    images: [
      "/images/stafftrol-1.png",
      "/images/stafftrol-2.png",
      "/images/stafftrol-3.png",
      "/images/stafftrol-4.png",
      "/images/stafftrol-5.png",
      "/images/stafftrol-6.png",
    ],
    tags: ["MongoDB", "Express", "React", "Node.js"],
    liveUrl: "https://stafftroltest.alphatrol.com",
  },
  {
    id: 6,
    title: "Elevate (Elev8)",
    description: "Community-rooted social enterprise platform supporting Black and migrant creatives through leadership development, coaching, events, and entrepreneurship programmes.",
    images: [
      "/images/elevate-1.png",
      "/images/elevate-2.png",
      "/images/elevate-3.png",
      "/images/elevate-4.png",
      "/images/elevate-5.png",
      "/images/elevate-6.png",
    ],
    tags: ["Next.js", "React", "TypeScript", "Tailwind"],
    liveUrl: "https://eleva8.netlify.app/",
  },
  {
    id: 7,
    title: "Miragold Tutors",
    description: "Professional tutoring platform helping children excel in 11+ entrance exams through structured small-group lessons, mock exams, and personalised coaching.",
    images: [
      "/images/miragold-1.png",
      "/images/miragold-2.png",
      "/images/miragold-3.png",
      "/images/miragold-4.png",
      "/images/miragold-5.png",
      "/images/miragold-6.png",
    ],
    tags: ["Next.js", "React", "TypeScript", "Tailwind"],
    liveUrl: "https://miragoldtutors.com/",
  },
  {
    id: 8,
    title: "GHRI Foundation",
    description: "Nonprofit platform for the Global Health Reform Initiative Foundation, promoting equitable healthcare access through telemedicine, preventive care, and community health programmes.",
    images: [
      "/images/ghri-1.jpeg",
      "/images/ghri-2.jpeg",
      "/images/ghri-3.jpeg",
      "/images/ghri-4.jpeg",
      "/images/ghri-5.jpeg",
    ],
    tags: ["Next.js", "React", "TypeScript", "Tailwind"],
    liveUrl: "https://ghrif.org/",
  },
  {
    id: 9,
    title: "Luxero",
    description: "Elegant luxury watch e-commerce store with an authenticated timepiece marketplace, brand and collection search, escrow-protected checkout, and a global network of trusted dealers.",
    images: [
      "/images/luxero-1.png",
      "/images/luxero-2.png",
      "/images/luxero-3.png",
      "/images/luxero-4.png",
      "/images/luxero-5.png",
      "/images/luxero-6.png",
    ],
    tags: ["Next.js", "React", "TypeScript", "Tailwind"],
    liveUrl: "https://luxerowatchess.netlify.app/",
  },
  {
    id: 10,
    title: "FoodMe",
    description: "Cross-platform mobile health and meal tracking app with water intake and goal features.",
    images: [
      "/images/foodmeapp-1.png",
      "/images/foodmeapp-2.png",
      "/images/foodmeapp-3.png",
      "/images/foodmeapp-4.png",
      "/images/foodmeapp-5.png",
    ],
    tags: ["Mobile App", "React Native", "Expo", "Firebase"],
    liveUrl:
      "https://expo.dev/accounts/jaybosco/projects/FoodMeApp/builds/decc78fc-9112-4870-9a13-22219d7f8f88",
  },
  {
    id: 11,
    title: "KDN",
    description: "Nigerian news aggregator app delivering trending stories across politics, entertainment, business, and culture, with category browsing and bookmarking.",
    images: [
      "/images/kdn-1.jpg",
      "/images/kdn-2.jpg",
      "/images/kdn-3.jpg",
      "/images/kdn-4.jpg",
      "/images/kdn-5.jpg",
    ],
    tags: ["Mobile App", "React Native", "Expo", "Fastify"],
    liveUrl: "https://expo.dev/accounts/jaybosco/projects/new-mobile-app-kdnnn/builds/9aa3e309-e878-4b1d-b8a4-4ba590c252f7",
  },
  {
    id: 12,
    title: "Igbodate",
    description: "Igbo culture-focused social and dating app blending matchmaking with community features — regional group chats, a short-video feed, post creation, direct messaging, and a creator rewards programme.",
    images: [
      "/images/igbodate-1.jpeg",
      "/images/igbodate-2.jpeg",
      "/images/igbodate-3.jpeg",
      "/images/igbodate-4.jpeg",
      "/images/igbodate-5.jpeg",
      "/images/igbodate-6.jpeg",
      "/images/igbodate-7.jpeg",
      "/images/igbodate-8.jpeg",
    ],
    tags: ["Mobile App", "React Native", "Expo", "Node.js", "Socket.io"],
    liveUrl: "https://igbodate.com",
  },

];

export const certificates: Certificate[] = [
  {
    id: 1,
    title: "JavaScript Algorithms and Data Structures",
    issuer: "freeCodeCamp",
    date: "August 31, 2022",
    image: "/images/cert-1.png",
    verifyUrl: "https://freecodecamp.org/certification/jay-bosco/javascript-algorithms-and-data-structures",
  },
  {
    id: 2,
    title: "Front-End Development Libraries",
    issuer: "freeCodeCamp",
    date: "December 24, 2022",
    image: "/images/cert-2.png",
    verifyUrl: "https://freecodecamp.org/certification/jay-bosco/front-end-development-libraries",
  },
  {
    id: 3,
    title: "Responsive Web Design",
    issuer: "freeCodeCamp",
    date: "July 10, 2026",
    image: "/images/cert-3.png",
    verifyUrl: "https://freecodecamp.org/certification/jay-bosco/responsive-web-design",
  },
  {
    id: 4,
    title: "Legacy Front-End",
    issuer: "freeCodeCamp",
    date: "July 15, 2026",
    image: "/images/cert-4.png",
    verifyUrl: "https://freecodecamp.org/certification/jay-bosco/legacy-front-end",
  },
];

export const services: Service[] = [
  {
    icon: "fa-solid fa-laptop-code",
    title: "Frontend Development",
    short: "I specialise in HTML, CSS/SCSS, JavaScript, and Bootstrap.",
    full: "I build beautiful and responsive interfaces with frameworks like React.js, Angular, and tools like Tailwind to improve UI/UX performance.",
  },
  {
    icon: "fa-solid fa-laptop-code",
    title: "Back End Development",
    short: "Skilled in backend frameworks and server-side logic.",
    full: "I use technologies like Node.js, Python, PHP, Laravel, Firebase, SQL, MongoDB, and ASP.NET to build robust and secure web applications.",
  },
  {
    icon: "fa-solid fa-mobile",
    title: "Mobile Development",
    short: "I develop full-stack mobile apps using React Native.",
    full: "With tools like Node.js, Expo, NoSQL, Firebase, and Git, I build cross-platform mobile apps that are fast, functional, and user-friendly.",
  },
];
